update: lint-staged config added.

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,40 +1,45 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+# Stop the process and return false to
+ctrl_c() {
+  echo "Stoping checks..."
+  false
+}
+
+# ctrl_c is the name of the signal ctrl_c function for SIGINT signal
+trap "ctrl_c" SIGINT
+
 echo
-echo "Styling, testing and building project before committing..."
-
-# # Code format using prettier
-# npm run format && echo "Code format successful." || (
-#     echo "Code format failed !!!"
-#     echo "Check the error and fix the warning(s) or error(s)."
-#     false;
-# )
-
-# Lint check
-npm run eslint:check && echo "lint check successful." || (
-    echo "Prettier Check Failed."
-    echo "Run 'npm run eslint:fix', add changes and try commit again."; 
-    false;
-)
+echo "Pre-commit checks started..."
 
 # Check tsconfig standards
 npm run typescript:check && echo "type check successful." || (
-    echo "Failed Type check !!!"
-    echo "Make the changes required above."
-    false;
+  echo "Failed Type check !!!"
+  echo "Make the changes required above."
+  false
 )
+echo
+
+# Code format using prettier
+npm run lint-staged && echo "Code format successful, and added to staging." || (
+  echo "Code format failed !!!"
+  echo "Check the error and fix the warning(s) or error(s)."
+  false
+)
+echo
 
 # Build check
 npm run build && echo "Build successful." || (
-    echo "Build failed !!!"
-    echo "Next build failed: View the errors above to see why."
-    false;
+  echo "Build failed !!!"
+  echo "Next build failed: View the errors above to see why."
+  false
 )
+echo
 
-# If ctrl+c is pressed stop the process
-
-echo "Check and add the formatted codes to staging."
 echo "All checks completed."
+exit 0
 
-# echo "Uncomment all the checks!!!"
+# Wait till all the steps and checks completes.
+sleep 300 # 5mins
+exit 0
